version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /backend/SkillPath.Api
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /backend/SkillPath.Api.Tests
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
