// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillPath.Api.Data;

#nullable disable

namespace SkillPath.Api.Data.Migrations
{
    [DbContext(typeof(SkillPathDbContext))]
    [Migration("20260819163323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SkillPath.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Status", "Status IN ('active', 'disabled', 'deleted')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.Certification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<short>("MockQuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Certifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Certifications_MockQuestionCount", "MockQuestionCount > 0");

                            t.HasCheckConstraint("CK_Certifications_Status", "Status IN ('active', 'retired', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.CertificationModule", b =>
                {
                    b.Property<long>("CertificationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("CertificationId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("CertificationModules", null, t =>
                        {
                            t.HasCheckConstraint("CK_CertificationModules_Weight", "Weight IS NULL OR (Weight >= 0 AND Weight <= 100)");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.CertificationQuestion", b =>
                {
                    b.Property<long>("CertificationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("CertificationId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("CertificationQuestions", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.ExamAttemptQuestion", b =>
                {
                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<short>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("QuestionAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExamAttemptId", "Position");

                    b.HasIndex("QuestionAttemptId")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.HasIndex("ExamAttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("ExamAttemptQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamAttemptQuestions_Position", "Position > 0");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.ExamAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CertificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("ExamAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamAttempts_Duration", "DurationSeconds IS NULL OR DurationSeconds >= 0");

                            t.HasCheckConstraint("CK_ExamAttempts_Score", "Score IS NULL OR Score >= 0");

                            t.HasCheckConstraint("CK_ExamAttempts_Status", "Status IN ('in_progress', 'completed', 'abandoned')");

                            t.HasCheckConstraint("CK_ExamAttempts_Total", "Total IS NULL OR Total > 0");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("LearningAreas", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningAreas_Status", "Status IN ('planned', 'published', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("LearningPathId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId", "Slug")
                        .IsUnique();

                    b.HasIndex("LearningPathId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Modules", null, t =>
                        {
                            t.HasCheckConstraint("CK_Modules_Status", "Status IN ('draft', 'published', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningPath", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("LearningAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("LearningAreaId", "SortOrder");

                    b.ToTable("LearningPaths", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningPaths_Level", "Level IN ('beginner', 'intermediate', 'advanced')");

                            t.HasCheckConstraint("CK_LearningPaths_Status", "Status IN ('draft', 'published', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<short?>("EstimatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Slug")
                        .IsUnique();

                    b.HasIndex("ModuleId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Lessons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lessons_EstimatedMinutes", "EstimatedMinutes IS NULL OR EstimatedMinutes > 0");

                            t.HasCheckConstraint("CK_Lessons_Status", "Status IN ('draft', 'published', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.LessonCompletion", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "CompletedAt");

                    b.ToTable("LessonCompletions", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CertificationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LearningPathId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("PracticeSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PracticeSessions_Mode", "Mode IN ('quick', 'weak_areas', 'mistakes', 'module')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionData")
                        .HasColumnType("TEXT");

                    b.Property<int>("LegacyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableData")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.ToTable("Questions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Questions_ContentType", "ContentType IN ('knowledge_check', 'practice_question', 'mock_question')");

                            t.HasCheckConstraint("CK_Questions_Difficulty", "Difficulty IN ('beginner', 'intermediate', 'advanced')");

                            t.HasCheckConstraint("CK_Questions_InteractionData", "InteractionData IS NULL OR json_valid(InteractionData)");

                            t.HasCheckConstraint("CK_Questions_Mode", "Mode IN ('quiz', 'reveal', 'read')");

                            t.HasCheckConstraint("CK_Questions_Status", "Status IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("CK_Questions_TableData", "TableData IS NULL OR json_valid(TableData)");

                            t.HasCheckConstraint("CK_Questions_Type", "QuestionType IN ('multiple_choice', 'yes_no', 'drag_drop', 'hotspot', 'self_grade')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PracticeSessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseData")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ExamAttemptId", "SubmittedAt");

                    b.HasIndex("PracticeSessionId", "SubmittedAt");

                    b.HasIndex("UserId", "QuestionId", "SubmittedAt");

                    b.ToTable("QuestionAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_QuestionAttempts_Duration", "DurationSeconds IS NULL OR DurationSeconds >= 0");

                            t.HasCheckConstraint("CK_QuestionAttempts_OneSession", "NOT (PracticeSessionId IS NOT NULL AND ExamAttemptId IS NOT NULL)");

                            t.HasCheckConstraint("CK_QuestionAttempts_ResponseData", "ResponseData IS NULL OR json_valid(ResponseData)");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionAttemptSelection", b =>
                {
                    b.Property<Guid>("QuestionAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuestionOptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionAttemptId", "QuestionOptionId");

                    b.HasIndex("QuestionOptionId");

                    b.ToTable("QuestionAttemptSelections", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionModule", b =>
                {
                    b.Property<long>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionId", "ModuleId");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasFilter("IsPrimary = 1");

                    b.HasIndex("ModuleId", "QuestionId");

                    b.ToTable("QuestionModules", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "OptionKey")
                        .IsUnique();

                    b.HasIndex("QuestionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserPathEnrollment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LearningPathId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CurrentLessonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LearningPathId");

                    b.HasIndex("CurrentLessonId");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("UserId", "LastActivityAt");

                    b.ToTable("UserPathEnrollments", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserPreferences_Theme", "Theme IN ('light', 'dark', 'system')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProgressDocuments", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.CertificationModule", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.LearningModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.CertificationQuestion", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.ExamAttemptQuestion", b =>
                {
                    b.HasOne("SkillPath.Api.Models.ExamAttemptRecord", null)
                        .WithMany()
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.QuestionAttempt", null)
                        .WithMany()
                        .HasForeignKey("QuestionAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.ExamAttemptRecord", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningModule", b =>
                {
                    b.HasOne("SkillPath.Api.Models.LearningPath", null)
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningPath", b =>
                {
                    b.HasOne("SkillPath.Api.Models.LearningArea", null)
                        .WithMany()
                        .HasForeignKey("LearningAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.Lesson", b =>
                {
                    b.HasOne("SkillPath.Api.Models.LearningModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.LessonCompletion", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.PracticeSession", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.LearningPath", null)
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionAttempt", b =>
                {
                    b.HasOne("SkillPath.Api.Models.ExamAttemptRecord", null)
                        .WithMany()
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.PracticeSession", null)
                        .WithMany()
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionAttemptSelection", b =>
                {
                    b.HasOne("SkillPath.Api.Models.QuestionAttempt", null)
                        .WithMany()
                        .HasForeignKey("QuestionAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.QuestionOption", null)
                        .WithMany()
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionModule", b =>
                {
                    b.HasOne("SkillPath.Api.Models.LearningModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionOption", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserPathEnrollment", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Lesson", null)
                        .WithMany()
                        .HasForeignKey("CurrentLessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.LearningPath", null)
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserPreference", b =>
                {
                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithOne()
                        .HasForeignKey("SkillPath.Api.Models.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserProgress", b =>
                {
                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithOne()
                        .HasForeignKey("SkillPath.Api.Models.UserProgress", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
