// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillPath.Api.Data;

#nullable disable

namespace SkillPath.Api.Data.Migrations
{
    [DbContext(typeof(SkillPathDbContext))]
    partial class SkillPathDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillPath.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('learner', 'admin')");

                            t.HasCheckConstraint("CK_Users_Status", "\"Status\" IN ('active', 'disabled', 'deleted')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.Certification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("MockQuestionCount")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Certifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Certifications_MockQuestionCount", "\"MockQuestionCount\" > 0");

                            t.HasCheckConstraint("CK_Certifications_Status", "\"Status\" IN ('active', 'retired', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.CertificationModule", b =>
                {
                    b.Property<long>("CertificationId")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("CertificationId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("CertificationModules", null, t =>
                        {
                            t.HasCheckConstraint("CK_CertificationModules_Weight", "\"Weight\" IS NULL OR (\"Weight\" >= 0 AND \"Weight\" <= 100)");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.CertificationQuestion", b =>
                {
                    b.Property<long>("CertificationId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("DomainName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("CertificationId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("CertificationQuestions", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.ContentRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("EntityType", "EntityId", "ChangedAt");

                    b.HasIndex("EntityType", "EntityId", "Version")
                        .IsUnique();

                    b.ToTable("ContentRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentRevisions_ChangeType", "\"ChangeType\" IN ('seeded', 'created', 'updated', 'published', 'unpublished', 'reordered', 'archived')");

                            t.HasCheckConstraint("CK_ContentRevisions_EntityType", "\"EntityType\" IN ('module', 'lesson')");

                            t.HasCheckConstraint("CK_ContentRevisions_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.ExamAttemptQuestion", b =>
                {
                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("uuid");

                    b.Property<short>("Position")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("QuestionAttemptId")
                        .HasColumnType("uuid");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.HasKey("ExamAttemptId", "Position");

                    b.HasIndex("QuestionAttemptId")
                        .IsUnique();

                    b.HasIndex("QuestionId");

                    b.HasIndex("ExamAttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("ExamAttemptQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamAttemptQuestions_Position", "\"Position\" > 0");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.ExamAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CertificationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Total")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("ExamAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamAttempts_Duration", "\"DurationSeconds\" IS NULL OR \"DurationSeconds\" >= 0");

                            t.HasCheckConstraint("CK_ExamAttempts_Score", "\"Score\" IS NULL OR \"Score\" >= 0");

                            t.HasCheckConstraint("CK_ExamAttempts_Status", "\"Status\" IN ('in_progress', 'completed', 'abandoned')");

                            t.HasCheckConstraint("CK_ExamAttempts_Total", "\"Total\" IS NULL OR \"Total\" > 0");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("LearningAreas", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningAreas_Status", "\"Status\" IN ('planned', 'published', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("LearningPathId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId", "Slug")
                        .IsUnique();

                    b.HasIndex("LearningPathId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Modules", null, t =>
                        {
                            t.HasCheckConstraint("CK_Modules_Status", "\"Status\" IN ('draft', 'published', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningPath", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("LearningAreaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("LearningAreaId", "SortOrder");

                    b.ToTable("LearningPaths", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningPaths_Level", "\"Level\" IN ('beginner', 'intermediate', 'advanced')");

                            t.HasCheckConstraint("CK_LearningPaths_Status", "\"Status\" IN ('draft', 'published', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("EstimatedMinutes")
                        .HasColumnType("smallint");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Slug")
                        .IsUnique();

                    b.HasIndex("ModuleId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Lessons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lessons_EstimatedMinutes", "\"EstimatedMinutes\" IS NULL OR \"EstimatedMinutes\" > 0");

                            t.HasCheckConstraint("CK_Lessons_Status", "\"Status\" IN ('draft', 'published', 'archived')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.LessonCompletion", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "CompletedAt");

                    b.ToTable("LessonCompletions", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CertificationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LearningPathId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("PracticeSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PracticeSessions_Mode", "\"Mode\" IN ('quick', 'weak_areas', 'mistakes', 'module')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("InteractionData")
                        .HasColumnType("jsonb");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("LegacyId")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceAttribution")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TableData")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.ToTable("Questions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Questions_ContentType", "\"ContentType\" IN ('knowledge_check', 'practice_question', 'mock_question')");

                            t.HasCheckConstraint("CK_Questions_Difficulty", "\"Difficulty\" IN ('beginner', 'intermediate', 'advanced')");

                            t.HasCheckConstraint("CK_Questions_InteractionType", "\"InteractionType\" IN ('single_choice', 'multiple_choice', 'yes_no', 'unordered_selection', 'fixed_match', 'ordering', 'dropdown', 'yes_no_matrix', 'image_self_grade', 'image_hotspot')");

                            t.HasCheckConstraint("CK_Questions_Mode", "\"Mode\" IN ('quiz', 'reveal', 'read')");

                            t.HasCheckConstraint("CK_Questions_Status", "\"Status\" IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("CK_Questions_Type", "\"QuestionType\" IN ('multiple_choice', 'yes_no', 'drag_drop', 'hotspot', 'self_grade')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExamAttemptId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PracticeSessionId")
                        .HasColumnType("uuid");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseData")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ExamAttemptId", "SubmittedAt");

                    b.HasIndex("PracticeSessionId", "SubmittedAt");

                    b.HasIndex("UserId", "QuestionId", "SubmittedAt");

                    b.ToTable("QuestionAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_QuestionAttempts_Duration", "\"DurationSeconds\" IS NULL OR \"DurationSeconds\" >= 0");

                            t.HasCheckConstraint("CK_QuestionAttempts_OneSession", "NOT (\"PracticeSessionId\" IS NOT NULL AND \"ExamAttemptId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionAttemptSelection", b =>
                {
                    b.Property<Guid>("QuestionAttemptId")
                        .HasColumnType("uuid");

                    b.Property<long>("QuestionOptionId")
                        .HasColumnType("bigint");

                    b.HasKey("QuestionAttemptId", "QuestionOptionId");

                    b.HasIndex("QuestionOptionId");

                    b.ToTable("QuestionAttemptSelections", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionModule", b =>
                {
                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("QuestionId", "ModuleId");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = TRUE");

                    b.HasIndex("ModuleId", "QuestionId");

                    b.ToTable("QuestionModules", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "OptionKey")
                        .IsUnique();

                    b.HasIndex("QuestionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserPathEnrollment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("LearningPathId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CurrentLessonId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "LearningPathId");

                    b.HasIndex("CurrentLessonId");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("UserId", "LastActivityAt");

                    b.ToTable("UserPathEnrollments", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserPreferences_Theme", "\"Theme\" IN ('light', 'dark', 'system')");
                        });
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProgressDocuments", (string)null);
                });

            modelBuilder.Entity("SkillPath.Api.Models.CertificationModule", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.LearningModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.CertificationQuestion", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.ContentRevision", b =>
                {
                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SkillPath.Api.Models.ExamAttemptQuestion", b =>
                {
                    b.HasOne("SkillPath.Api.Models.ExamAttemptRecord", null)
                        .WithMany()
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.QuestionAttempt", null)
                        .WithMany()
                        .HasForeignKey("QuestionAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.ExamAttemptRecord", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningModule", b =>
                {
                    b.HasOne("SkillPath.Api.Models.LearningPath", null)
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.LearningPath", b =>
                {
                    b.HasOne("SkillPath.Api.Models.LearningArea", null)
                        .WithMany()
                        .HasForeignKey("LearningAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.Lesson", b =>
                {
                    b.HasOne("SkillPath.Api.Models.LearningModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.LessonCompletion", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.PracticeSession", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.LearningPath", null)
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionAttempt", b =>
                {
                    b.HasOne("SkillPath.Api.Models.ExamAttemptRecord", null)
                        .WithMany()
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.PracticeSession", null)
                        .WithMany()
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionAttemptSelection", b =>
                {
                    b.HasOne("SkillPath.Api.Models.QuestionAttempt", null)
                        .WithMany()
                        .HasForeignKey("QuestionAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.QuestionOption", null)
                        .WithMany()
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionModule", b =>
                {
                    b.HasOne("SkillPath.Api.Models.LearningModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.QuestionOption", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserPathEnrollment", b =>
                {
                    b.HasOne("SkillPath.Api.Models.Lesson", null)
                        .WithMany()
                        .HasForeignKey("CurrentLessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SkillPath.Api.Models.LearningPath", null)
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserPreference", b =>
                {
                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithOne()
                        .HasForeignKey("SkillPath.Api.Models.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillPath.Api.Models.UserProgress", b =>
                {
                    b.HasOne("SkillPath.Api.Models.AppUser", null)
                        .WithOne()
                        .HasForeignKey("SkillPath.Api.Models.UserProgress", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
